/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Property } from './Property.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PropertyService } from './Property.service';
import { PropertyController } from './Property.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Property])],
  providers: [PropertyService],
  exports: [PropertyService],
  controllers: [PropertyController],
})
export class PropertyModule {}
