import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class LeaseAgreementCreate {
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  monthly_rent: string;
}

export class LeaseAgreement {
  @ApiProperty()
  id: number;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  monthly_rent: string;
}
