/**
 * This file generated by Apso.
 */
import { PropertyModule } from './Property/Property.module';
import { TenantModule } from './Tenant/Tenant.module';
import { LeaseAgreementModule } from './LeaseAgreement/LeaseAgreement.module';
import { MaintenanceRequestModule } from './MaintenanceRequest/MaintenanceRequest.module';

export default [
  PropertyModule,
  TenantModule,
  LeaseAgreementModule,
  MaintenanceRequestModule,
];
