/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Tenant, TenantCreate } from './dtos/Tenant.dto';
import { TenantController } from './Tenant.controller';
import { TenantService } from './Tenant.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('TenantController', () => {
  let controller: TenantController;
  let spyService: TenantService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: TenantService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [TenantController],
      providers: [TenantService, ApiServiceProvider],
    }).compile();

    controller = module.get<TenantController>(TenantController);
    spyService = module.get<TenantService>(TenantService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call TenantController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call TenantController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Tenant();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
