/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Tenant } from './Tenant.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TenantService } from './Tenant.service';
import { TenantController } from './Tenant.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Tenant])],
  providers: [TenantService],
  exports: [TenantService],
  controllers: [TenantController],
})
export class TenantModule {}
