/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  LeaseAgreement,
  LeaseAgreementCreate,
} from './dtos/LeaseAgreement.dto';
import { LeaseAgreementController } from './LeaseAgreement.controller';
import { LeaseAgreementService } from './LeaseAgreement.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('LeaseAgreementController', () => {
  let controller: LeaseAgreementController;
  let spyService: LeaseAgreementService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: LeaseAgreementService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [LeaseAgreementController],
      providers: [LeaseAgreementService, ApiServiceProvider],
    }).compile();

    controller = module.get<LeaseAgreementController>(LeaseAgreementController);
    spyService = module.get<LeaseAgreementService>(LeaseAgreementService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call LeaseAgreementController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call LeaseAgreementController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new LeaseAgreement();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
