/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  LeaseAgreement,
  LeaseAgreementCreate,
} from './dtos/LeaseAgreement.dto';
import { LeaseAgreementService } from './LeaseAgreement.service';

@Crud({
  model: {
    type: LeaseAgreement,
  },
  dto: {
    create: LeaseAgreementCreate,
    update: LeaseAgreement,
    replace: LeaseAgreement,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('LeaseAgreements')
@ApiTags('LeaseAgreements')
export class LeaseAgreementController
  implements CrudController<LeaseAgreement>
{
  constructor(public service: LeaseAgreementService) {}

  get base(): CrudController<LeaseAgreement> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple LeaseAgreements' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single LeaseAgreement' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single LeaseAgreement' })
  @ApiBody({
    type: LeaseAgreementCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: LeaseAgreement) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleLeaseAgreements' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<LeaseAgreement>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single LeaseAgreement' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: LeaseAgreement) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single LeaseAgreement' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: LeaseAgreement,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single LeaseAgreement' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
