/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { LeaseAgreement } from './LeaseAgreement.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { LeaseAgreementService } from './LeaseAgreement.service';
import { LeaseAgreementController } from './LeaseAgreement.controller';

@Module({
  imports: [TypeOrmModule.forFeature([LeaseAgreement])],
  providers: [LeaseAgreementService],
  exports: [LeaseAgreementService],
  controllers: [LeaseAgreementController],
})
export class LeaseAgreementModule {}
