/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { MaintenanceRequest } from './MaintenanceRequest.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { MaintenanceRequestService } from './MaintenanceRequest.service';
import { MaintenanceRequestController } from './MaintenanceRequest.controller';

@Module({
  imports: [TypeOrmModule.forFeature([MaintenanceRequest])],
  providers: [MaintenanceRequestService],
  exports: [MaintenanceRequestService],
  controllers: [MaintenanceRequestController],
})
export class MaintenanceRequestModule {}
