/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import {
  MaintenanceRequest,
  MaintenanceRequestCreate,
} from './dtos/MaintenanceRequest.dto';
import { MaintenanceRequestService } from './MaintenanceRequest.service';

@Crud({
  model: {
    type: MaintenanceRequest,
  },
  dto: {
    create: MaintenanceRequestCreate,
    update: MaintenanceRequest,
    replace: MaintenanceRequest,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('MaintenanceRequests')
@ApiTags('MaintenanceRequests')
export class MaintenanceRequestController
  implements CrudController<MaintenanceRequest>
{
  constructor(public service: MaintenanceRequestService) {}

  get base(): CrudController<MaintenanceRequest> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple MaintenanceRequests' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single MaintenanceRequest' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single MaintenanceRequest' })
  @ApiBody({
    type: MaintenanceRequestCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: MaintenanceRequest,
  ) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleMaintenanceRequests' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<MaintenanceRequest>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single MaintenanceRequest' })
  update(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: MaintenanceRequest,
  ) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single MaintenanceRequest' })
  replace(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: MaintenanceRequest,
  ) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single MaintenanceRequest' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
