/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import {
  MaintenanceRequest,
  MaintenanceRequestCreate,
} from './dtos/MaintenanceRequest.dto';
import { MaintenanceRequestController } from './MaintenanceRequest.controller';
import { MaintenanceRequestService } from './MaintenanceRequest.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('MaintenanceRequestController', () => {
  let controller: MaintenanceRequestController;
  let spyService: MaintenanceRequestService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: MaintenanceRequestService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [MaintenanceRequestController],
      providers: [MaintenanceRequestService, ApiServiceProvider],
    }).compile();

    controller = module.get<MaintenanceRequestController>(
      MaintenanceRequestController,
    );
    spyService = module.get<MaintenanceRequestService>(
      MaintenanceRequestService,
    );
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call MaintenanceRequestController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call MaintenanceRequestController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new MaintenanceRequest();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
