import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class MaintenanceRequestCreate {
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
}

export class MaintenanceRequest {
  @ApiProperty()
  id: number;
  @ApiProperty()
  description: string;
  @ApiProperty()
  status: string;
}
